
version: '3.9'

services:
  mysql:
    ports:
      - 3307:3306
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: dbtest
        target: /var/lib/mysql
  php:
    ports:
        - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony5/certs
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/vendor
    environment:
      DATABASE_URL: "mysql://root:root@mysql/symfony-sandbox?serverVersion=8.0.26"
  # node:
  #   network_mode: 'host'
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.encore.dev
  #   volumes:
  #     - type: volume
  #       source: tls
  #       target: /root/.symfony5/certs
  #     - type: volume
  #       target: /app/node_modules
  #     - type: bind
  #       target: /app
  #       source: .

volumes:
  dbtest:
  tls: